[server]
# Performance settings
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
runOnSave = false

# UI settings
port = 8501
address = "0.0.0.0"
headless = false

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[global]
developmentMode = false
logLevel = "info"
unitTest = false
suppressDeprecationWarnings = true

[client]
caching = true
displayEnabled = true
showErrorDetails = false